const projectClassifications = [
        { value: 'sector/advertising', label: 'Sector/Advertising'},
        { value: 'sector/agriculture', label: 'Sector/Agriculture'},
        { value: 'sector/architecture', label: 'Sector/Architecture'},
        { value: 'sector/automotive', label: 'Sector/Automotive'},
        { value: 'sector/aviation', label: 'Sector/Aviation'},
        { value: 'sector/banking', label: 'Sector/Banking'},
        { value: 'sector/business', label: 'Sector/Business'},
        { value: 'sector/construction', label: 'Sector/Construction'},
        { value: 'sector/design', label: 'Sector/Design'},
        { value: 'sector/fashion-design', label: 'Sector/Fashion-Design'},
        { value: 'sector/graphic-design', label: 'Sector/Graphic-Design'},
        { value: 'sector/interior-design', label: 'Sector/Interior-Design'},
        { value: 'sector/economics', label: 'Sector/Economics'},
        { value: 'sector/engineering', label: 'Sector/Engineering'},
        { value: 'sector/entrepreneurship', label: 'Sector/Entrepreneurship'},
        { value: 'sector/health-care', label: 'Sector/Health-Care'},
        { value: 'sector/education', label: 'Sector/Education'},
        { value: 'sector/management', label: 'Sector/Management'},
        { value: 'sector/robotics', label: 'Sector/Robotics'},
        { value: 'sector/marketing', label: 'Sector/Marketing'},
        { value: 'sector/social-media', label: 'Sector/Social-Media'},
        { value: 'sector/web-design', label: 'Sector/Web-Design'},
        { value: 'sector/web-development', label: 'Sector/Web-Development'},
        { value: 'sector/personal-finance', label: 'Sector/Personal-Finance'},
        { value: 'sector/investment', label: 'Sector/Investment'},
        { value: 'sector/energy', label: 'Sector/Energy'},
        { value: 'sector/real-estate', label: 'Sector/Real-Estate'},
        { value: 'sector/retail', label: 'Sector/Retail'},
        { value: 'sector/sales', label: 'Sector/Sales'},
        { value: 'sector/law', label: 'Sector/Law'},
        { value: 'sector/small-business', label: 'Sector/Small-Business' },
        { value: 'sector/not-for-profit', label: 'Sector/Not-For-Profit' },
        { value: 'sector/Academic', label: 'Sector/Academic' },
         // ARTS
        { value: 'arts/visual-arts', label: 'Arts/Visual Arts' },
        { value: 'arts/literature', label: 'Arts/Literature' },
        { value: 'arts/music', label: 'Arts/Music' },
        { value: 'arts/theater', label: 'Arts/Theater' },
        { value: 'arts/dance', label: 'Arts/Dance' },
        { value: 'arts/photography', label: 'Arts/Photography' },
        { value: 'arts/film', label: 'Arts/Film' },
        { value: 'arts/sculpture', label: 'Arts/Sculpture' },
        { value: 'arts/painting', label: 'Arts/Painting' },
        { value: 'arts/digital-art', label: 'Arts/Digital Art' },
        { value: 'arts/ceramics', label: 'Arts/Ceramics' },
        { value: 'arts/illustration', label: 'Arts/Illustration' },
        { value: 'arts/fashion', label: 'Arts/Fashion' },
        { value: 'arts/graphic-design', label: 'Arts/Graphic Design' },
        { value: 'arts/animation', label: 'Arts/Animation' },
        // TRAVEL
        { value: 'travel/adventure', label: 'Travel/Adventure' },
        { value: 'travel/beach-holidays', label: 'Travel/Beach Holidays' },
        { value: 'travel/cruises', label: 'Travel/Cruises' },
        { value: 'travel/cultural-trips', label: 'Travel/Cultural Trips' },
        { value: 'travel/family-travel', label: 'Travel/Family Travel' },
        { value: 'travel/food-wine-trips', label: 'Travel/Food & Wine Trips' },
        { value: 'travel/hiking-trekking', label: 'Travel/Hiking & Trekking' },
        { value: 'travel/honeymoons', label: 'Travel/Honeymoons' },
        { value: 'travel/luxury-travel', label: 'Travel/Luxury Travel' },
        { value: 'travel/nature-wildlife', label: 'Travel/Nature & Wildlife' },
        { value: 'travel/road-trips', label: 'Travel/Road Trips' },
        { value: 'travel/ski-snowboard', label: 'Travel/Ski & Snowboard' },
        { value: 'travel/spa-wellness', label: 'Travel/Spa & Wellness' },
        { value: 'travel/urban-travel', label: 'Travel/Urban Travel' },
        { value: 'travel/volunteering', label: 'Travel/Volunteering' },
        { value: 'travel/weekend-getaways', label: 'Travel/Weekend Getaways' },
        { value: 'travel/ecotourism', label: 'Travel/Ecotourism' },
        { value: 'travel/solo-travel', label: 'Travel/Solo Travel' },
        // SPORTS 
        { value: 'sports/american-football', label: 'Sports/American Football' },
        { value: 'sports/baseball', label: 'Sports/Baseball' },
        { value: 'sports/basketball', label: 'Sports/Basketball' },
        { value: 'sports/cricket', label: 'Sports/Cricket' },
        { value: 'sports/soccer', label: 'Sports/Soccer' },
        { value: 'sports/tennis', label: 'Sports/Tennis' },
        { value: 'sports/volleyball', label: 'Sports/Volleyball' },
        { value: 'sports/hockey', label: 'Sports/Hockey' },
        { value: 'sports/golf', label: 'Sports/Golf' },
        { value: 'sports/rugby', label: 'Sports/Rugby' },
        { value: 'sports/martial-arts', label: 'Sports/Martial Arts' },
        { value: 'sports/boxing', label: 'Sports/Boxing' },
        { value: 'sports/wrestling', label: 'Sports/Wrestling' },
        { value: 'sports/track-and-field', label: 'Sports/Track and Field' },
        { value: 'sports/cycling', label: 'Sports/Cycling' },
        { value: 'sports/swimming', label: 'Sports/Swimming' },
        { value: 'sports/diving', label: 'Sports/Diving' },
        { value: 'sports/gymnastics', label: 'Sports/Gymnastics' },
        { value: 'sports/skiing', label: 'Sports/Skiing' },
        { value: 'sports/snowboarding', label: 'Sports/Snowboarding' },
        { value: 'sports/skating', label: 'Sports/Skating' },
        { value: 'sports/surfing', label: 'Sports/Surfing' },
        { value: 'sports/mountain-biking', label: 'Sports/Mountain Biking' },
        { value: 'sports/triathlon', label: 'Sports/Triathlon' },
        { value: 'sports/rock-climbing', label: 'Sports/Rock Climbing' },
        { value: 'sports/badminton', label: 'Sports/Badminton' },
        { value: 'sports/table-tennis', label: 'Sports/Table Tennis' },
        { value: 'sports/e-sports', label: 'Sports/E-Sports' },
        { value: 'sports/running', label: 'Sports/Running' },
        { value: 'sports/handball', label: 'Sports/Handball' },
        { value: 'sports/kayaking', label: 'Sports/Kayaking' },
        { value: 'sports/rowing', label: 'Sports/Rowing' },
        { value: 'sports/sailing', label: 'Sports/Sailing' },
        { value: 'sports/horse-riding', label: 'Sports/Horse Riding' },
        { value: 'sports/polo', label: 'Sports/Polo' },
        { value: 'sports/fencing', label: 'Sports/Fencing' },
        { value: 'sports/archery', label: 'Sports/Archery' },
        { value: 'sports/shooting', label: 'Sports/Shooting' },
        { value: 'sports/bodybuilding', label: 'Sports/Bodybuilding' },
        // Social issues 
        { value: 'social-issues/charity-and-causes', label: 'Social Issues/Charity and Causes' },
        { value: 'social-issues/philantropy', label: 'Social Issues/Philantropy' },
        { value: 'social-issues/community-issues', label: 'Social Issues/Community Issues' },
        { value: 'social-issues/environmentalism', label: 'Social Issues/Environmentalism' },
        { value: 'social-issues/sustainability', label: 'Social Issues/Sustainability' },
        { value: 'social-issues/volunteering', label: 'Social Issues/Volunteering' },
        //DYI
        { value: 'diy/home-improvement', label: 'DIY/Home Improvement' },
        { value: 'diy/furniture-making', label: 'DIY/Furniture Making' },
        { value: 'diy/gardening', label: 'DIY/Gardening' },
        { value: 'diy/crafts', label: 'DIY/Crafts' },
        { value: 'diy/painting-and-decor', label: 'DIY/Painting and Decor' },
        { value: 'diy/sewing-and-textiles', label: 'DIY/Sewing and Textiles' },
        { value: 'diy/electronics', label: 'DIY/Electronics' },
        { value: 'diy/plumbing', label: 'DIY/Plumbing' },
        { value: 'diy/woodworking', label: 'DIY/Woodworking' },
        { value: 'diy/metalworking', label: 'DIY/Metalworking' },
        { value: 'diy/upcycling', label: 'DIY/Upcycling' },
        { value: 'diy/automotive-repair', label: 'DIY/Automotive Repair' },
        { value: 'diy/landscaping', label: 'DIY/Landscaping' },
        { value: 'diy/knitting-and-crochet', label: 'DIY/Knitting and Crochet' },
        { value: 'diy/jewelry-making', label: 'DIY/Jewelry Making' },
        { value: 'diy/papercraft', label: 'DIY/Papercraft' },
        { value: 'diy/home-automation', label: 'DIY/Home Automation' },
        { value: 'diy/3d-printing', label: 'DIY/3D Printing' },
        { value: 'diy/cosmetics-and-beauty', label: 'DIY/Cosmetics and Beauty' },
        // SCIENCE
        { value: 'science/biology', label: 'Science/Biology' },
        { value: 'science/chemistry', label: 'Science/Chemistry' },
        { value: 'science/physics', label: 'Science/Physics' },
        { value: 'science/astronomy', label: 'Science/Astronomy' },
        { value: 'science/geology', label: 'Science/Geology' },
        { value: 'science/meteorology', label: 'Science/Meteorology' },
        { value: 'science/oceanography', label: 'Science/Oceanography' },
        { value: 'science/environmental-science', label: 'Science/Environmental Science' },
        { value: 'science/neuroscience', label: 'Science/Neuroscience' },
        { value: 'science/genetics', label: 'Science/Genetics' },
        { value: 'science/medicine', label: 'Science/Medicine' },
        { value: 'science/biochemistry', label: 'Science/Biochemistry' },
        { value: 'science/anthropology', label: 'Science/Anthropology' },
        { value: 'science/archaeology', label: 'Science/Archaeology' },
        { value: 'science/paleontology', label: 'Science/Paleontology' },
        { value: 'science/psychology', label: 'Science/Psychology' },
        { value: 'science/sociology', label: 'Science/Sociology' },
        { value: 'science/mathematics', label: 'Science/Mathematics' },
        { value: 'science/biotechnology', label: 'Science/Biotechnology' },
        { value: 'science/nanotechnology', label: 'Science/Nanotechnology' },
        { value: 'science/computer-science', label: 'Science/Computer Science' },
        { value: 'science/ecology', label: 'Science/Ecology' },
        { value: 'science/zoology', label: 'Science/Zoology' },
        { value: 'science/botany', label: 'Science/Botany' },
        { value: 'science/microbiology', label: 'Science/Microbiology' },
        { value: 'science/pharmacology', label: 'Science/Pharmacology' },
        { value: 'science/philosophy-of-science', label: 'Science/Philosophy of Science' },
        { value: 'science/epidemiology', label: 'Science/Epidemiology' },
        { value: 'science/immunology', label: 'Science/Immunology' },
        { value: 'science/toxicology', label: 'Science/Toxicology' },
]
export const sortedProjectClassifications = [...projectClassifications].sort((a, b) => a.label.localeCompare(b.label));
  
export default projectClassifications;  
