const projectClassifications = [
    { value: 'diy', label: 'DIY Project' },
    { value: 'blog', label: 'Blog' },
    { value: 'home-reno', label: 'Home Renovations' },
    { value: 'garden-landscaping', label: 'Garden Landscaping' },
    { value: 'fitness-goal', label: 'Personal Fitness Goals' },
    { value: 'personal-film', label: 'Personal Film Projects' },
    { value: 'language-learning', label: 'Learning a New Language' },
    { value: 'software', label: 'Software' },
    { value: 'travel', label: 'Travel' },
    { value: 'cooking', label: 'Cooking' },
    { value: 'home-improvement', label: 'Home Improvement' },
    { value: 'art', label: 'Art' },
    { value: 'fashion', label: 'Fashion'},
    { value: 'music', label: 'Music' },
    { value: 'writing', label: 'Writing' },
    { value: 'film', label: 'Film & Video' },
    { value: 'photography', label: 'Photography' },
    { value: 'crafts', label: 'Crafts' },
    { value: 'fashion', label: 'Fashion & Design' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'research', label: 'Research' },
    { value: 'education', label: 'Education & Courses' },
    { value: 'events', label: 'Events Planning' },
    { value: 'health', label: 'Health & Fitness' },
    { value: 'gardening', label: 'Gardening' },
    { value: 'environment', label: 'Environmental Projects' },
    { value: 'volunteering', label: 'Volunteering & Social Work' },
    { value: 'sports', label: 'Sports & Athletics' },
    { value: 'dance', label: 'Dance' },
    { value: 'business', label: 'Business & Startups' },
    { value: 'nonprofit', label: 'Nonprofit & Activism' },
    { value: 'pets', label: 'Pets & Animals' },
    { value: 'tech', label: 'Technology & Gadgets' },
    { value: 'science', label: 'Science & Exploration' },
    { value: 'automotive', label: 'Automotive & Mechanics' },
    { value: 'beauty', label: 'Beauty & Cosmetics' },
    { value: 'real-estate', label: 'Real Estate & Property' }, 
    { value: 'spirituality', label: 'Spirituality & Meditation' },
    { value: 'furniture', label: 'Furniture Building' },
    { value: 'podcasting', label: 'Podcasting' },
    { value: 'vlogging', label: 'Vlogging' },
    { value: 'comics', label: 'Comics & Graphic Novels' },
    { value: 'martial-arts', label: 'Martial Arts' },
    { value: 'magic', label: 'Magic & Illusions' },
    { value: 'culinary-arts', label: 'Culinary Arts' },
    { value: 'woodworking', label: 'Woodworking' },
    { value: 'sculpture', label: 'Sculpture' },
    { value: 'pottery', label: 'Pottery & Ceramics' },
    { value: 'philanthropy', label: 'Philanthropy' },
    { value: 'public-speaking', label: 'Public Speaking' },
    { value: 'adventure-sports', label: 'Adventure Sports' },
    { value: 'aerobics', label: 'Aerobics' },
    { value: 'aquatics', label: 'Aquatics & Water Activities' },
    { value: 'birdwatching', label: 'Bird Watching' },
    { value: 'brewing', label: 'Home Brewing' },
    { value: 'calligraphy', label: 'Calligraphy' },
    { value: 'candle-making', label: 'Candle Making' },
    { value: 'collecting', label: 'Collecting (e.g. stamps, coins)' },
    { value: 'community-projects', label: 'Community Projects' },
    { value: 'cosplay', label: 'Cosplay' },
    { value: 'documentary', label: 'Documentary Making' },
    { value: 'drama-theater', label: 'Drama & Theater' },
    { value: 'embroidery', label: 'Embroidery' },
    { value: 'genealogy', label: 'Genealogy & Family Trees' },
    { value: 'horticulture', label: 'Horticulture' },
    { value: 'kite-making', label: 'Kite Making & Flying' },
    { value: 'knitting', label: 'Knitting & Crocheting' },
    { value: 'magic-tricks', label: 'Magic Tricks' },
    { value: 'modeling', label: 'Modeling (e.g. planes, trains)' },
    { value: 'origami', label: 'Origami & Paper Crafting' },
    { value: 'personal-finance', label: 'Personal Finance & Investing' },
    { value: 'poetry', label: 'Poetry & Literature' },
    { value: 'puzzles', label: 'Puzzles & Brain Games' },
    { value: 'quilting', label: 'Quilting' },
    { value: 'robotics', label: 'Robotics & AI' },
    { value: 'rpg', label: 'Role-Playing Games (RPG)' },
    { value: 'singing', label: 'Singing & Vocal Training' },
    { value: 'sketching', label: 'Sketching & Drawing' },
    { value: 'storytelling', label: 'Storytelling & Writing' },
    { value: 'yoga', label: 'Yoga & Pilates' },
    { value: 'urban-farming', label: 'Urban Farming & Gardening' },
    { value: 'wildlife-conservation', label: 'Wildlife Conservation' },
    { value: 'welding', label: 'Welding & Metalwork' },
    { value: 'toys-making', label: 'Toys Making' },
    { value: 'tattooing', label: 'Tattooing & Body Art' },
    { value: 'gallery-exhibition', label: 'Gallery Exhibitions'},
    { value: 'art-commission', label: 'Artwork Commissions' },
    { value: 'digital-art', label: 'Digital Art' },
    { value: 'portraiture-project', label: 'Portraiture Projects' },
    { value: 'animation-short', label: 'Animation Shorts' },
    { value: 'artistic-video', label: 'Artistic Video' },
    { value: 'awareness-campaign', label: 'Community Awareness Campaigns' },
    { value: 'fundraiser', label: 'Fundraisers for Causes' },
    { value: 'volunteer-recruitment', label: 'Volunteer Recruitment' },
    { value: 'rehab-program', label: 'Rehabilitation Programs' },
    { value: 'refugee-support', label: 'Refugee Support and Resettlement' },
    { value: 'course-project', label: 'Course Project' },
    { value: 'thesis-project', label: 'Thesis or Capstone Project' },
    { value: 'internship-search', label: 'Internship Search and Applications' },
    { value: 'exchange-program', label: 'Student Exchange Programs' },
    { value: 'sports-club', label: 'Sports Club' },
    { value: 'school-application', label: 'School Application' },
    { value: 'tutoring', label: 'Tutoring' },
    { value: 'research-proposal', label: 'Research Proposal Writing' },
    { value: 'field-study', label: 'Field Study or Expedition' },
    { value: 'academic-conference', label: 'Academic Conference Presentation' },
    { value: 'collaborative-research', label: 'Collaborative Research Invitations' },
    { value: 'publication-assistance', label: 'Research Publication Assistance' },
    { value: 'grant-application', label: 'Grant and Funding Applications' },
    { value: 'data-collection', label: 'Data Collection Initiatives' },
    { value: 'peer-review-request', label: 'Peer Review Requests' },
    { value: 'course-development', label: 'Course Development and Curriculum Planning' },
    { value: 'lab-experiment', label: 'Lab Experimentations' },
    {value: 'research-proposal', label: 'Research Proposal Writing' },
    { value: 'field-study', label: 'Field Study or Expedition' },
    { value: 'academic-conference', label: 'Academic Conference Presentation' },
    { value: 'collaborative-research', label: 'Collaborative Research Invitations' },
    { value: 'publication-assistance', label: 'Research Publication Assistance' },
    { value: 'grant-application', label: 'Grant and Funding Applications' },
    { value: 'data-collection', label: 'Data Collection Initiatives' },
    { value: 'peer-review-request', label: 'Peer Review Requests' },
    { value: 'course-development', label: 'Course Development and Curriculum Planning' },
    { value: 'lab-experiment', label: 'Lab Experimentations' },
    { value: 'brand-collaboration', label: 'Brand Collaboration Proposals' },
    { value: 'content-creation', label: 'Content Creation Ideas' },
    { value: 'fan-engagement', label: 'Fan Engagement Events' },
    { value: 'merchandise-launch', label: 'Merchandise Launches' },
    { value: 'workshop-hosting', label: 'Hosting Workshops or Masterclasses' },
    { value: 'giveaway-planning', label: 'Giveaway Planning' },
    { value: 'channel-growth', label: 'Channel Growth Strategies' },
    { value: 'pr-campaign', label: 'Public Relations Campaigns' },
    { value: 'affiliate-program', label: 'Affiliate Program Recommendations' },
    { value: 'content-schedule', label: 'Content Scheduling and Calendar Planning' },
    { value: 'venue-scouting', label: 'Venue Scouting and Recommendations' },
    { value: 'vendor-negotiations', label: 'Vendor Negotiations and Deals' },
    { value: 'event-promotion', label: 'Event Promotion' },
    { value: 'ticket-sales', label: 'Ticket Sales and Distribution' },
    { value: 'volunteer-recruitment', label: 'Event Volunteer Recruitment' },
    { value: 'sponsorship-pitch', label: 'Sponsorship Pitching and Partnerships' },
    { value: 'event-branding', label: 'Event Branding' },
    { value: 'guest-list-management', label: 'Guest List Management' },
    { value: 'event-feedback', label: 'Post-Event Feedback and Analysis' },
    { value: 'team-formation', label: 'Team Formation & Recruitment' },
    { value: 'sports-coaching', label: 'Sports Coaching & Training' },
    { value: 'tournament-organization', label: 'Tournament & League Organization' },
    { value: 'fitness-routine', label: 'Fitness Routine & Workout Plans' },
    { value: 'sports-equipment-reviews', label: 'Sports Equipment Reviews & Recommendations' },
    { value: 'athlete-nutrition', label: 'Athlete Nutrition & Diet Plans' },
    { value: 'injury-rehab', label: 'Injury Rehabilitation & Therapy' },
    { value: 'sports-psychology', label: 'Sports Psychology & Mental Training' },
    { value: 'sponsorship-deals', label: 'Sponsorship Deals & Athlete Branding' },
    { value: 'fan-engagement-events', label: 'Fan Engagement & Community Events' },
    { value: 'sports-analytics', label: 'Sports Analytics & Performance Analysis' },
    { value: 'sports-merchandising', label: 'Sports Merchandising & Branding' },
    { value: 'sports-tech', label: 'Sports Technology & Innovation' },
    { value: 'sports-camp', label: 'Sports Camps & Clinics' },
]
  export default projectClassifications;