import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const { data } = api.projects.getAll.useQuery();


  const { user } = useUser();


  return (
    <>
      <Head>
        <title>Riples</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full border-x-8 md:max-w-2xl">
          <div className="mb-4">
            {!user && <SignInButton />}
            {!!user && (<SignOutButton />)}
          </div>
          <div className="mt-4">
            {/* proj get all data */}
            {data?.map((project) => (<div key={project.id}> {project.title} </div>) )}
          </div>
        </div>
      </main>
    </>
  );
}
