name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_KEY_BOTS: ${{ secrets.OPENAI_API_KEY_BOTS }}
      NEXT_PUBLIC_S3_PUBLIC_IMAGES_BUCKET:  ${{ secrets.NEXT_PUBLIC_S3_PUBLIC_IMAGES_BUCKET }}
      S3_PUBLIC_IMAGES_BUCKET_ACCESS_KEY_ID:  ${{ secrets.S3_PUBLIC_IMAGES_BUCKET_ACCESS_KEY_ID }}
      S3_PUBLIC_IMAGES_BUCKET_ACCESS_KEY_SECRET:  ${{ secrets.S3_PUBLIC_IMAGES_BUCKET_ACCESS_KEY_SECRET }}
      FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
      FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GITHUB_ID: ${{ secrets.GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
      LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
      LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
      
    strategy:
      matrix:
        node-version: [16.x] # Adjust this if you're using a different version of Node.js

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Type check with TypeScript
      run: npx tsc --noEmit
    - name: Lint code
      run: npm run lint # Assuming you have a "lint" script in your package.json
